### PR TITLE
redesigned interface

### PR DESCRIPTION
**Pull request by qiyunzhu**
screenshot

### CODE REVIEW

**Comment by qiyunzhu** [comment]
Performed rigorous redesign of the interface as well as the code structure, including:

Code structure:
1. Uses a single master object `mo` to host all information handled by the program. It contains data, view, status, selected and binned contigs, etc.
2. The `mo` object is initiated during the window load event, and passed to subsequent modules.
3. There is no global variable.
4. In the future, the `mo` object can be exported / imported as a JSON file.

Interface design:
1. Has three panels above the canvas and stick to the viewport edge:
  - A start button at the top left corner, with a foldable dash board which mainly include controls of the whole plot.
  - A side frame at the right side, with lists of actual contents (bins, selected, masked) and controls over each of them.
  - A widget panel at the bottom left corner, which includes single-button switches (e.g., screenshot, reset).
2. Main plot and side panels can be manually resized and the plot will be scaled accordingly.
3. Dynamically show/hide panels upon user click and data change.
4. Uses flexbox to replace classical float and table in many cases.

**Comment by qiyunzhu** [comment]
Hello @fedarko @cameronmartino I am resuming the development of BinaRena. This weekend I did some re-structuring. I would like to keep you updated. Feel free to let me know any comments and suggestions!

Here is a live demo (changes will become effective after merging):
https://qiyunzhu.github.io/binarena/demo.html

**Comment by fedarko** [comment]
@qiyunzhu, this looks really nice. I'm super impressed!

I'm attaching a few comments here. These are just thoughts -- feel free to use them as you'd like.

## Application
- I love how polished the interface is. The search and polygon functionalities are super, super useful.

- This is a very small thing, but it might be nice to add "median" to the summary statistics available in the right panel on selected contigs (in addition to "mean" and "sum"). Personally I don't mind that it isn't there, but some people might want it to be an option.

- It looks like the screenshot produced by the screenshot button doesn't include the highlighting "status" of selected contigs (so highlighted contigs don't show up as blue). This isn't that important, but showing highlighted contigs in the screenshots could be a nice feature.

- I've tried it with multiple datasets, and it looks like failing to set a variable for `Size` will result in an empty display until you set something as `Size`. If possible, it might be nice to just default to a uniform size of `1` for all contigs if no field is set (so that the user isn't confused).

  - If there **needs** to be a variable set for `Size`, I would suggest modifying the interface to make this clearer (e.g. coloring the `x-axis`, `y-axis`, and `size` fields red if they are empty).

- It might be worth checking if the `metaKey` (see [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent)) is selected in addition to checking if the `shiftKey` is selected in [interface.js](https://github.com/qiyunzhu/binarena/blob/f12b4478acdcb939833cddc5507012270dcbc2b1/static/js/interface.js). This maps to the "command" key on a Mac, which I've seen used in a similar manner to the "shift" key in a few contexts. (This is of course very minor, though :)

- On the metagenome dataset I showed you earlier today, it looks like showing the grid just crashes the application (it covers the entire display gray). We can talk about this later in the week -- it might be something wrong with the dataset, so no worries!

## Code
- The code seems really clean from what I've seen so far. This will make adding more tests down the road a lot easier, which is great!

   - I've started to learn more about JS testing recently due to rankratioviz -- in the future I can try to help with adding tests.

- This is a small thing, but there technically are some global objects produced by BinaRena -- the functions contained in the various JS files (e.g. `calcArenaDimensions()` in `render.js`) are part of the namespace. However, since there aren't any third-party libraries used, this shouldn't be a problem.

  - I think the "proper" way to get around this is using something like Webpack / Rollup / RequireJS to pass around dependencies, but that is probably overkill for BinaRena. The way it is now is totally fine :)

Super excited to see where this goes!

**Comment by qiyunzhu** [comment]
Hi @fedarko ! Thank you for testing and commenting on the program! Your suggestions are like a project report :) Many suggestions are very inspiring.

I am improving the code to address individual suggestions. In this update, I resolved the `size` issue. Meanwhile, I optimized the rendering engine. It is now significantly faster with large datasets. There is still room for improvement, which I have identified but haven't done.

The program has lots of independent functions. It is true that in JS, functions are also variables. To completely avoid functions, one has to do a full OOP with functions being methods of classes. I chose not to do it because designing will be quite unintuitive with this complex interface. Also there are debates on OOP vs functional programming.

I will work bit more later today to address some other comments.

**Comment by qiyunzhu** [comment]
Added a cool function: interactive legend! @fedarko 

Screenshot from 2019-04-26 12-43-33

**Comment by fedarko** [comment]
This looks super cool! Thanks for letting me know :)

**Comment by qiyunzhu** [comment]
Added a few more functions, including continuous and discrete coloring, as well as some "smart rules" and interface improvements. @fedarko I also added a function you requested a long time ago: let the user toggle X- and Y-axes.

Screenshot from 2019-04-28 11-20-28

**Pull request merged**
